### ISSUE TITLE
Upgrade to Webpack v2 and React Router v4

### ISSUE THREAD

**Issue by cheton** [AimeeShen/react-redux-boilerplate#1]
Both webpack v1 and react-router v2 are outdated, consider upgrading to webpack v2 and react router v4 for newly created projects. 😃

**Comment by AimeeShen** [comment]
@cheton  Thank you for reminding, I was planning on catching up as well, time to upgrade my real project now 😆

ef95983 Upgrade to webpack2 and update webpack.config
9a5add8 Upgrade react-router to 4.x, and upgrade react-router-redux
